### PR TITLE
update google map api

### PR DESCRIPTION
**Pull request by yvo2m**
quick dirty fix :
- communicate through document.title instead of window.status
- move from QWebKit to QWebEngine
- web debugger does not work
- center map on SV position does not work

### CODE REVIEW

**Comment by enricofer** [comment]
Hi, your contribution is much appreciated!
Unfortunately I was already working on dropping Qt webkit and the new release is almost finished and all plugin features are now fixed, but you can still help me to test it and report issues: https://github.com/enricofer/go2streetview/tree/v10
only the pdf print,remains to be fixed. But it's an obsolete feature and we can think to remove from plugin.
Thank you anyway.

**Comment by yvo2m** [comment]
Great you use QWebChannel for passing message from JS to python !

for the pdf print, line 479 :
change :
` webview.page().mainFrame().render(painter)
`
  to 
` webview.render(painter)
`

**Comment by enricofer** [comment]
If you agree I could disable print menu item for now, in the meanwhile you could investigate how to reimplement and improve it

**Comment by yvo2m** [comment]
yes you can, but it was working in my patch ( except for the integration of the BE view)

**Comment by yvo2m** [comment]
Another issue I corrected, if you navigate in the SV window, then you resize the windows, you came back to the first position (quite annoying)

corrected by adding in setPosition (go2streetview.py), line 670 :

        self.pointWgs84 = actualWGS84 #save position in case of window resize
        self.heading=float(self.actualPOV['heading']) #save heading in case of window resize

**Comment by yvo2m** [comment]
If you don't mind, I will make minors comment there, instead of smalls Pull Request.

**Comment by yvo2m** [comment]
in setPosition (go2streetview.py), line 677 :
`
self.canvas.setCenter(actualSRS)`
always make my QGIS crashes

**Comment by enricofer** [comment]
I see, but at the moment I don't realize why.
I would hide the option for now.

**Comment by enricofer** [comment]
> in setPosition (go2streetview.py), line 677 : ` self.canvas.setCenter(actualSRS)` always make my QGIS crashes

fixed

> I found a bug, when you click an drag on the map to open a SV view, the heading drawn on the map is always to the north. The heading is correct once you move in the SV view.
> 
> Replacing all the `window.status = JSON.stringify` by `backend.catchJSevents(JSON.stringify` in the g2sv.html solve the issue.
> 

I think this was related to digitize on streetview new feature (green spot) and I have already fixed it 

> And could you please take into account this :
> 
> > Another issue I corrected, if you navigate in the SV window, then you resize the windows, you came back to the first position (quite annoying)
> > corrected by adding in setPosition (go2streetview.py), line 670 :
> > ```
> >     self.pointWgs84 = actualWGS84 #save position in case of window resize
> >     self.heading=float(self.actualPOV['heading']) #save heading in case of window resize
> > ```

Ok. I see what you mean.
Why don't you send a PR ?
Now master branch should be aligned with last plugin version

**Pull request closed without merging**
